# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d2f11b7c8255282ce01a41dda2507e6bd9726e1f497dab89823b9cea5723b167e89f2f79ea0c0e036247416b6c859fd4489bfa681f2f8c1b662073a94b0c7ed

test:
  secret_key_base: 711365c074a60336d12f5e12e07bdb0933b564491b789eb54135743c23d094744f66afa889ab437504ee7a4b0caaa89a3cab5640792fbdab71500e538214e067

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
